# Generated by Django 4.0.6 on 2022-07-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0021_add_property_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugsystem',
            name='api_url',
        ),
    ]
