# Generated by Django 4.0.6 on 2022-07-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0022_remove_bugsystem_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugsystem',
            name='api_url',
            field=models.CharField(blank=True, help_text='This is the URL to which API requests will be sent. Leave empty to disable!', max_length=1024, null=True, verbose_name='API URL'),
        ),
    ]
