# Generated by Django 4.0.6 on 2022-07-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0023_bugsystem_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugsystem',
            name='api_password',
        ),
        migrations.RemoveField(
            model_name='bugsystem',
            name='api_username',
        ),
    ]
