# Generated by Django 4.0.6 on 2022-07-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0024_remove_bugsystem_api_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugsystem',
            name='api_password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='API password or token'),
        ),
        migrations.AddField(
            model_name='bugsystem',
            name='api_username',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='API username'),
        ),
    ]
